
audit:
  - name: currency-dollar
    label: Tech Due Dilligence
    description: |
      Investors need to understand the technical risk of their investments. Usually by the time
      a Venture Captial or Private Equity firm are having Tech Due Dilligence performed they're
      confident in the business prospect. Tech Due Dilligence provides an understanding of technical 
      risks and expectations to address them in subsequent months and years after investment. 
      There are a few common questions investors want answered. 
    content: |
      Does the product roadmap, scale, and solution align with the growth targets of the fund raise? 
      Does the team have the right personel or understand which hires need to be made? Does the company
      have the organizational maturative of technical experience, processes, and culture required at
      their stage? 
    color: 
    experience: 
    years: 
    url:
    website_url:
    domain: 
  - name: currency-dollar
    label: Tech Debt
    description: |
      Tech Debt is a way to leverage technology to support near term business objectives at the expense 
      of technology cost later. Tech Debit something to expect at any stage of product development, but
      how much Tech Debt a company can tollerate depends on how their team and product are structured.
    color: 
    experience: 
    years: 
    url:
    website_url:
    domain: 
  - name: currency-dollar
    label: Performance
    description: |
      Application performance impacts the customer experience and cost businesses money. There is the operational cost, but also the cost of lost customers. 
      Perceived slowness causes frustration leading to user's losing patience and interest in the product. We'll take a holistic perspective to 
      understand the full stack performance profile of products to understand where the most value to the customers and ultimately the business comes from.
      Improvements to performance yield improvements to the companies bottom line. You can't improve what you can't measure
    color: 
    experience: 
    years: 
    url:
    website_url:
    domain: 
  - name: currency-dollar
    label: Testing
    description: |
      Automated testing provides consistency and reliability of existing product offerings when releasing new features
      or enhancements. You can't optimize confidently without test coverage.
    color: 
    experience: 
    years: 
    url:
    website_url:
    domain: 
  - name: currency-dollar
    label: CI/CD
    description: |
      Automated continuous integration and deployments increase team efficiency and enhance the developer experience. 
      Automated testing is only one aspected, but code quality and consistency as well as Infrastructure as Code build 
      phases ensure the code and the platform it runs on are in peak shape.
    color: 
    experience: 
    years: 
    url:
    website_url:
    domain: 
  - name: currency-dollar
    label: Scaling
    description: |
      Scaling issues can be found across the stack frontend load times, web request response times, request queueing delay, 
      background jobs queueing, and database query structure, indexing, and, you guess it, also queueing. Scaling automation requires the right metrics to trigger alarms 
      and scaling events appropriately.
    color: 
    experience: 
    years: 
    url:
    website_url:
    domain: 
  - name: currency-dollar
    label: Developer Experience
    description: |
      A happy team is a productive team. Codebases, DevOps, database administration, workflows, and automations make the developer's
      lives better and their performance improves when they're not stuck doing tedious and manual maintenance work.
    color: 
    experience: 
    years: 
    url:
    website_url:
    domain: 
  - name: currency-dollar
    label: Product Process
    description: |
      Having processes that empower teams enable the team to perform at their best. Processes should get out of the way of progress.
      A good workflow that a team can agree upon, but be flexible enough to change with growth is crucial to sustainable productivity.
    color: 
    experience: 
    years: 
    url:
    website_url:
    domain: 
business:
  - name: currency-dollar
    label: Lean Startup Workshop
    description: |
      You have an idea you want to bring to life? Maybe you think it's time to pay a developer to build an app. Before you spend time
      and a lot of money building something, make sure it's something users want. Know what will be built before you go into development.
      Validate that you understand who your users are by working through exercises in workflows, user stories, diagrams, and get user 
      feedback on product ideas and designs that can be adapted to their needs with less cost than code.
    color: 
    experience: 
    years: 
    url:
    website_url:
    domain: 
design:
  - name: currency-dollar
    label: Product Design
    description: |
      Product design is more important than product development. I'm a developer and I've seen too many build before design and struggle 
      to launch sucessfully. A design first approach allows you to iterate quickly and get valuable feedback before you spend a dime on 
      development. Design cycles cost less than development cycles and their is less of a sunk cost falisy at play. You can throw away part
      of a design more readily than code that's already been written. Design is about constraints and removal all that is not essential until
      you're left with what is necessary.
    content: |
     "Perfection is achieved not when there is nothing more to add but when there is nothing left to take away."
     "The value of a creative product doesn't lie in how much there is, but in how much has been discarded. 
     "When in doubt, leave it out."
     "Less is more"
    color: 
    experience: 
    years: 
    url:
    website_url:
    domain: 
  - name: currency-dollar
    label: User Stories
    description: |
      Part of the product design process is working through the user's journey through user stories. This allows you to layout your ideas
      of what a user is coming to your product to accomplish and prioritize what is crucial to deliver initially. You can then iterate to 
      your ultimate vision or follow the feedback of your users as they use the product. This is an opportunity to also consider what 
      information you can gather from the user's journey in order to make informed decisions based on analytics later on.
    color: 
    experience: 
    years: 
    url:
    website_url:
    domain: 
  - name: currency-dollar
    label: Workflow Diagrams
    description: |
      Workflow diagrams are a great way to visually layout user experiences from an interaction perspective. Taking user stories and mapping them out into workflow diagrams helps to determine where their might be unforeseen steps in the process.
      As you map out the journey you have to consider, how a user gets from this step in the journey to that step. Maybe there is an automated 
      process that needs to connect the two, like a verification messsage or maybe there is a user experience you hadn't considered. Workflow 
      diagrams map out the user stories into a story board you can walk through more visually without even having to wireframe or prototype.
    color: 
    experience: 
    years: 
    url:
    website_url:
    domain: 
  - name: currency-dollar
    label: Wireframes
    description: |
      Low fidelity wireframes help to start understanding how to reduce complexity exposed to the users visual experience. Simplicity in the user 
      interface will yield less friction than overwhelming numbers of visual elements for users to decide where to go next. It's always easier to add,
      but the real opportunity comes from removing uncessary distractions. Wire frames are an ideal time to get user feedback on their expectations of a
      user interface at a particular step in the user experience without their opinion of the visual design getting in the way. You'll learn what the 
      user's intentions and expectations on when they ask questions. You'll also learn what their stuggles are when they don't know what they're expected 
      to do next. 
    color: 
    experience: 
    years: 
    url:
    website_url:
    domain: 
  - name: currency-dollar
    label: Prototypes
    description: |
      High fidelity clickable mockups using tools like Figma, Invision, or similar are a powerful mechinism for validating design before your build.
      Give users a chance to experience your designs and take advantage of the opportunity to learn from their real experience rather than your imagined
      expectations.
    color: 
    experience: 
    years: 
    url:
    website_url:
    domain: 
  - name: currency-dollar
    label: Architecture Diagrams
    description: 
    color: 
    experience: 
    years: 
    url:
    website_url:
    domain: 
development:
  - name: currency-dollar
    label: Product Development
    description: 
    color: 
    experience: 
    years: 
    url:
    website_url:
    domain: 
  - name: currency-dollar
    label: Development Experience Improvement
    description: 
    color: 
    experience: 
    years: 
    url:
    website_url:
    domain: 
  - name: currency-dollar
    label: Performance Enhancements
    description: 
    color: 
    experience: 
    years: 
    url:
    website_url:
    domain: 
  - name: currency-dollar
    label: Infrastructure Automations
    description: 
    color: 
    experience: 
    years: 
    url:
    website_url:
    domain: 
  - name: currency-dollar
    label: Software Upgrades
    description: 
    color: 
    experience: 
    years: 
    url:
    website_url:
    domain: 