
audit:
  - name: Tech Due Dilligence
    label: 
    description: 
    color: 
    experience: 
    years: 
    url:
    website_url:
    domain: 
  - name: Tech Debt
    label: 
    description: 
    color: 
    experience: 
    years: 
    url:
    website_url:
    domain: 
  - name: Performance
    label: 
    description: 
    color: 
    experience: 
    years: 
    url:
    website_url:
    domain: 
  - name: Testing
    label: 
    description: 
    color: 
    experience: 
    years: 
    url:
    website_url:
    domain: 
  - name: CI/CD
    label: 
    description: 
    color: 
    experience: 
    years: 
    url:
    website_url:
    domain: 
  - name: Scaling
    label: 
    description: 
    color: 
    experience: 
    years: 
    url:
    website_url:
    domain: 
  - name: Developer Experience
    label: 
    description: 
    color: 
    experience: 
    years: 
    url:
    website_url:
    domain: 
  - name: Product Process
    label: 
    description: 
    color: 
    experience: 
    years: 
    url:
    website_url:
    domain: 
business:
  - name: Lean Startup Workshop
    label: 
    description: 
    color: 
    experience: 
    years: 
    url:
    website_url:
    domain: 
design:
  - name: Product Design
    label: 
    description: 
    color: 
    experience: 
    years: 
    url:
    website_url:
    domain: 
  - name: User Stories
    label: 
    description: 
    color: 
    experience: 
    years: 
    url:
    website_url:
    domain: 
  - name: Workflow Diagrams
    label: 
    description: 
    color: 
    experience: 
    years: 
    url:
    website_url:
    domain: 
  - name: Architecture Diagrams
    label: 
    description: 
    color: 
    experience: 
    years: 
    url:
    website_url:
    domain: 
development:
  - name: Product Development
    label: 
    description: 
    color: 
    experience: 
    years: 
    url:
    website_url:
    domain: 
  - name: Development Experience Improvement
    label: 
    description: 
    color: 
    experience: 
    years: 
    url:
    website_url:
    domain: 
  - name: Performance Enhancements
    label: 
    description: 
    color: 
    experience: 
    years: 
    url:
    website_url:
    domain: 
  - name: Infrastructure Automations
    label: 
    description: 
    color: 
    experience: 
    years: 
    url:
    website_url:
    domain: 
  - name: Software Upgrades
    label: 
    description: 
    color: 
    experience: 
    years: 
    url:
    website_url:
    domain: 